AWSTemplateFormatVersion: "2010-09-09"
Description: IAM Druid Glue Policy

Parameters:
  OutputName:
    Type: String
    Description: Application name. Used to populate role descriptions.

Resources:
  Policy:
      Type: 'AWS::IAM::ManagedPolicy'
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: Assume
              Effect: Allow
              Action:
                - sts:AssumeRole # useful for explicit assume role
              Resource:
                - arn:aws:iam::492436075634:role/druid-admin-role-Role-SET2TUJYEJZT

Outputs:
  ExportPolicy:
    Value: !Ref Policy
    Export:
      Name: !Sub ${OutputName}

