AWSTemplateFormatVersion: "2010-09-09"
Description: IAM Druid Glue BASE Policy

Parameters:
  OutputName:
    Type: String
    Description: Application name. Used to populate role descriptions.

Resources:
  Policy:
      Type: 'AWS::IAM::ManagedPolicy'
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: DPUInstance
              Effect: Allow
              Action:
                - ec2:DescribeInstances
                - ec2:DescribeImages
                - ec2:DescribeInstanceTypes
                - ec2:DescribeKeyPairs
                - ec2:DescribeVpcs
                - ec2:DescribeVpcEndpoints
                - ec2:DescribeRouteTables
                - ec2:DescribeSubnets
                - ec2:DescribeSecurityGroups
                - ec2:CreateSecurityGroup
                - ec2:CreateNetworkInterface
                - ec2:DeleteNetworkInterface
                - ec2:DescribeNetworkInterfaces
                - ec2:DescribeVpcAttribute
                - ec2:CreateTags
                - ec2:DeleteTags
                - ec2:RunInstances
                - tag:GetResources
              Resource:
                - "*"
            - Sid: RequiredIAM
              Effect: Allow
              Action:
                - iam:ListRolePolicies
                - iam:GetRole
                - iam:GetRolePolicy
                - iam:PassRole
                - iam:ListRoles
                - iam:ListUsers
                - iam:ListGroups
                - iam:ListAttachedRolePolicies
                - iam:CreateRole
              Resource:
                - "*"
            - Sid: GlueMinimum
              Effect: Allow
              Action:
                - cloudwatch:PutMetricData # studio
                - cloudwatch:GetDashboard # studio
                - cloudwatch:ListDashboards # studio
                - glue:ListJobs # both glue and studio
                - glue:BatchGetJobs # both glue and studio
                - glue:GetJobRun # both glue and studio
                - glue:GetJobRuns # both glue and studio
                - glue:GetJob # studio and redundant
                - glue:GetJobs # studio and redundant
                - glue:ListTriggers
                - glue:BatchGetTriggers
                - glue:GetSecurityConfigurations
                - glue:GetTable  # studio
                - glue:GetTags  # studio
                - glue:GetTrigger  # studio
                - glue:GetTriggers  # studio
                - glue:GetDevEndpoint
                - glue:GetJobBookmark # studio
                - glue:BatchStopJobRun # studio
                - glue:CreateScript  # studio
                - glue:BatchDeleteJob # studio
                - glue:DeleteJob # glue console
                - glue:ResetJobBookmark  # studio
                - glue:ListWorkflows
                - glue:GetWorkflow
                - glue:GetWorkflowRun
                - glue:GetWorkflowRuns
                - glue:GetWorkflowRunProperties
                - glue:GetWorkflow
                - glue:BatchGetWorkflows
                - glue:BatchGetBlueprints
                - glue:ListBlueprints
                - glue:GetBlueprint
                - glue:GetBlueprintRun
                - glue:GetBlueprintRuns
                - glue:StartBlueprintRun
                - glue:CreateSchedule
                - glue:UpdateSchedule
                - glue:ListCrawlers
                - glue:GetCrawler
                - glue:GetCrawlers
                - glue:GetCrawlerMetrics
                - glue:BatchGetCrawlers
                - kms:ReEncrypt # studio
                - kms:GenerateDataKey # studio
                - kms:DescribeKey # studio
                - kms:Decrypt # studio
                - s3:GetBucketLocation # glue, studio and basics
                - s3:ListBucket # glue, studio and basics
                - s3:ListAllMyBuckets # glue, studio and basics
                - s3:GetBucketAcl # glue, studio and basics
                - support:*
              Resource:
                - "*"
            - Sid: GlueConnection
              Effect: Allow
              Action:
                - glue:GetConnections
                - glue:GetConnection
              Resource:
                - arn:aws:glue:*:492436075634:catalog
                - arn:aws:glue:*:492436075634:connection/*
            - Sid: logsui
              Effect: Allow
              Action:
                - logs:GetLogEvents
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                - logs:AssociateKmsKey
              Resource:
                - arn:aws:logs:*:*:/aws-glue/*
            - Sid: awssupport
              Effect: Allow
              Action:
                - support:*
              Resource:
                - "*"
            - Sid: secmanage
              Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - "*"
        Roles: ['AWSGlueServiceRole-druid-studio-Role-R7S6SYH3Y8EC']

Outputs:
  ExportPolicy:
    Value: !Ref Policy
    Export:
      Name: !Sub ${OutputName}