AWSTemplateFormatVersion: "2010-09-09"
Description: IAM Druid Glue Policy

Parameters:
  OutputName:
    Type: String
    Description: Application name. Used to populate role descriptions.

Resources:
  Policy:
      Type: 'AWS::IAM::ManagedPolicy'
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: VisualEditorAthena1
              Effect: Allow
              Action:
                - glue:GetDatabase
                - glue:GetPartition
                - glue:GetConnections
                - glue:GetTableVersion
                - glue:GetConnection
                - glue:GetTables
                - glue:GetTableVersions
                - glue:GetPartitions
                - glue:GetDatabases
                - glue:GetTable
                - glue:GetJob
                - glue:GetDevEndpoint
                - rds:*
              Resource:
                - arn:aws:glue:*:492436075634:catalog
#                - arn:aws:glue:*:492436075634:table/default/test_cc_nopart
#                - arn:aws:glue:*:492436075634:table/default/cc_intermediate_project
                - arn:aws:glue:*:492436075634:connection/*
#                - arn:aws:glue:*:492436075634:tableVersion/default/test_cc_nopart/*
#                - arn:aws:glue:*:492436075634:tableVersion/default/cc_intermediate_project/*
#                - arn:aws:glue:*:492436075634:database/default
#                - arn:aws:glue:*:492436075634:database/will_database
#                - arn:aws:glue:*:492436075634:table/will_database/*
#                - arn:aws:glue:*:492436075634:devEndpoint/willspark2
#            - Sid: DBConnect
#              Effect: Allow
#              Action:
#                - rds-db:connect
#              Resource:
#                - "*"
            - Sid: DBConnect
              Effect: Allow
              Action:
                - rds-db:connect
              Resource:
#                - arn:aws:rds-db:*:492436075634:dbuser:db-IAFBUH74DVK3SFTE54LDHSM4BY/rds_iam
                - arn:aws:rds-db:*:492436075634:dbuser:db-IAFBUH74DVK3SFTE54LDHSM4BY/iamglue
                - arn:aws:rds-db:*:492436075634:dbuser:cluster-46O6S65ONMWENP2SNPCSDWC7LE/iamglue
                - arn:aws:rds-db:*:492436075634:dbuser:*/*
            - Sid: DBSubnet
              Effect: Allow
              Action:
                - ec2:DescribeInstances
                - ec2:DescribeImages
                - ec2:DescribeInstanceTypes
                - ec2:DescribeKeyPairs
                - ec2:DescribeVpcs
                - ec2:DescribeVpcEndpoints
                - ec2:DescribeRouteTables
                - ec2:DescribeSubnets
                - ec2:DescribeSecurityGroups
                - ec2:CreateSecurityGroup
                - ec2:CreateNetworkInterface
                - ec2:DescribeVpcAttribute
                - ec2:CreateTags
                - ec2:DeleteTags
                - ec2:RunInstances
              Resource:
                 - "*"
            - Sid: Secret
              Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - arn:aws:secretsmanager:us-west-2:492436075634:secret:will_cms_test
                - arn:aws:secretsmanager:us-west-2:492436075634:secret:consortium_master
            - Sid: dmstask
              Effect: Allow
              Action:
                - dms:StartReplicationTask
              Resource:
                "*"

Outputs:
  ExportPolicy:
    Value: !Ref Policy
    Export:
      Name: !Sub ${OutputName}